FROM docker.io/library/rust:1.77-alpine AS builder
RUN apk add --no-cache musl-dev
WORKDIR /usr/src/app
COPY . .
RUN cargo build --release

FROM docker.io/library/alpine:3.19
WORKDIR /app
COPY --from=builder /usr/src/app/target/release/aeonboarding-backend /app/
EXPOSE 8080
CMD ["./aeonboarding-backend"]