# Stage 1: Build
FROM rust:1.94-slim AS builder 
WORKDIR /app

# Install dependencies sistem
RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*

# Copy manifest dan LOCK
COPY Cargo.toml Cargo.lock ./

# Copy hasil prepare dari host ke container agar bisa build offline
COPY .sqlx ./.sqlx
# Beritahu compiler untuk menggunakan mode offline
ENV SQLX_OFFLINE=true
# --------------------------

# Copy source code dan migrations
COPY src ./src
COPY migrations ./migrations

# Build release
RUN cargo build --release

# Stage 2: Runtime
FROM debian:bookworm-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Sesuaikan nama binary dengan yang ada di Cargo.toml 
COPY --from=builder /app/target/release/backend .

EXPOSE 8080
# Jika nama binary Anda adalah 'backend' (sesuai Cargo.toml yang Anda tunjukkan sebelumnya)
CMD ["./backend"]